version: '3'
services:
  rasa-server:
    image: rasa/rasa:2.8.1-full
    user: "1000"
    public: true
    ports:
      - '5007:5005'
    volumes:
      - ./:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api
#      - --log-file
#      - out.log
    depends_on:
      - action-server
    networks:
      - all
  action-server:
    image: rasa/rasa-sdk:2.8.5
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
